name: "Deployment Config"
description: "Merges all deployment configs into manifests."
inputs:
  source:
    description: "Source directory to parse deployment config from"
    required: true
  target:
    description: "Target directory to write deployment manifest to"
    required: true
  environment:
    description: "Environment to deploy to"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
